### ISSUE TITLE
Bug in camera screen

### ISSUE THREAD

**Issue by RikardF** [95joaols/Lab-schoolAssignments-#48]
Notice about selfie/boring do not always corresponds to correct camera view.

**Comment by AndreasGunnarsson** [comment]
I will however just remove it since I have no real way of testing it (the rear/back camera on my phone doesn't work). If anyone else wants to try to fix it feel free to do so. It's not really an essential feature anyway, it was mostly there for testing purposes in the beginning of the camera development..

**Comment by AndreasGunnarsson** [comment]
Gone.
